### ISSUE TITLE
Makefile?

### ISSUE THREAD

**Issue by orbea** [dimkr/loksh#13]
Any chance the Makefile can come back? It just worked and doesn't depend on python3. Thanks!

**Comment by dimkr** [comment]
The use of Meson makes it easier to maintain multiple projects that port OpenBSD userspace to Linux. See https://github.com/dimkr/loksh/compare/upstream/6.6...master - the diff is minimal, thanks to lolibc, a thin compatibility layer implemented as a Meson subproject. Makefiles don't allow this kind of easy embedding.

Feel free to maintain a fork of loksh with a Makefile, I'll do my best not to change things that might break it.

**Comment by orbea** [comment]
@dimkr Thanks for the quick response in that case I have a suggestion.

Use git subtrees instead of submodules. The automatic release tarballs provided by github will not have the submodules included while they will with git subtrees. The alternative is to provide your own release tarballs in the future with the submodules included.

See: https://www.atlassian.com/git/tutorials/git-subtree
