### ISSUE TITLE
Tarball with subprojects/ included

### ISSUE THREAD

**Issue by nmeum** [dimkr/loksh#16]
I am maintaining a loksh package for Alpine Linux. With the transition to meson and lolibc the `subprojects/lolibc` folder is not included in the [release tarball](https://github.com/dimkr/loksh/archive/6.7.tar.gz) would it be possible to create a tarball which includes the git submodule to ease packaging?

**Comment by dimkr** [comment]
GitHub auto-generates these tarballs and doesn't support vendoring.

Is it a problem to clone the git repository recursively, instead of using those tarballs?

**Comment by nmeum** [comment]
It would be an inconvenience, yes.

**Comment by dimkr** [comment]
Stay tuned, I'm releasing a 6.7.1, with a release tarball generated by CI.

**Comment by dimkr** [comment]
There you go: https://github.com/dimkr/loksh/releases/download/6.7.1/src.tar.xz.

Please let me know if there's anything else I can help with.

**Comment by orbea** [comment]
@dimkr Your tarball link is already dead.

Also please use standard tarball names of NAME-VERSION, so in this case `'loksh-6.7.1.tar.xz'`.

**Comment by dimkr** [comment]
@orbea It's weird that GitHub deleted it, I'll try to trigger a rebuild of this tag

**Comment by dimkr** [comment]
I issued a 6.7.2 release, identical to 6.7 and 6.7.1, to test CI and avoid overwriting files in previous releases.

**Comment by orbea** [comment]
Thanks, lets hope it doesn't get deleted this time.

**Comment by orbea** [comment]
Also, it would help to rename the directory before making the tarball so the extracted directory and the tarball directories name match. :)
