### ISSUE TITLE
Obsolete base

### ISSUE THREAD

**Issue by mirabilos** [dimkr/loksh#2]
Why don’t you just use mksh – https://www.mirbsd.org/mksh.htm – for your musl/Linux system?

No need to fork, port, etc. as mksh is modern and musl-ready.

**Comment by sskras** [comment]
> I don't need portability, since I use it under one platform and everything works right. 

I you did fork, you needed to improve exactly the portability.
That's what mksh provides out of the box, IIUC.

> if it's OpenBSD's default login shell, it must be good enough for most users. 

Surely for most OpenBSD users, not so clear about the usage on Linux.

> I'm sure it has bugs, but software sucks and I can't change that.

I think the @mirabilos idea was that mksh improves that aspect too. So you could :)
