### ISSUE TITLE
[request] attaching a release tarball

### ISSUE THREAD

**Issue by epsilon-0** [dimkr/loksh#23]
Would it be possible to add a release tarball like you did for `6.7.2` so that it contains the subprojects?
Currently downloading the tag does not download the subprojects and causes the build to fail.

Thanks,
Aisha

**Comment by dimkr** [comment]
Working on it, something is weird (Travis says the file has been uploaded, but the releases page says it wasn't).

**Comment by epsilon-0** [comment]
awesome :smile_cat:
