### ISSUE TITLE
CTRL is not defined when building 6.8 against musl

### ISSUE THREAD

**Issue by dimkr** [dimkr/loksh#30]

**Comment by wylfen** [comment]
Just ran into this on one of my musl systems, even with the patch applied (i.e with 6.8). Is there a reason the header is only included when `SMALL` is set? I'm building loksh against ncurses, so the header is never pulled in for me.

Also whilst I'm here, the version number in `meson.build` is still 6.7. Thanks!

**Comment by dimkr** [comment]
Somehow, CTRL  is defined when building against ncurses. I had to dig into headers, and found out that term.h or some other ncurses header eventually #includeded sys/ttydefaults.h, so CTRL is undefined only when SMALL.

**Comment by wylfen** [comment]
I've attached a [build log](https://github.com/dimkr/loksh/files/5434721/loksh-log.txt).

I'm using ncurses 6.2 and couldn't find `sys/ttydefaults.h` in any of its headers. Which header is it exactly that has it included for you?

**Comment by dimkr** [comment]
term.h (from ncursesw) includes termios.h, which includes sys/ttydefaults.h.
