### ISSUE TITLE
Change .kshrc location at compile time

### ISSUE THREAD

**Issue by toniz4** [dimkr/loksh#33]
There is any way to easily change the config file location at compile time? I prefer having my configs at ~/.config/ksh.

**Comment by dimkr** [comment]
Hi @toniz4! loksh behaves the same as upstream ksh, and extra features won't be added.

**Comment by toniz4** [comment]
So there is any way i can change a declare or a variable before compiling it to search for the kshrc in another location? To be clear i just want to change it locally.

**Comment by toniz4** [comment]
I should have RTFM. I can set the location of the .kshrc file with ENV at ~/.profile.
```
ENV="$XDG_CONFIG_HOME"/ksh/kshrc
```
